/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectobryanarita_eduardovaldez;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import java.util.Random;

/**
 *
 * @author BJAL
 */
public class Ahorcado extends javax.swing.JFrame {

    Random rndm = new Random();
    public ImageIcon imagenes[];
    public JButton botones[];
    public String mensajes[];
    public int rango;
    public int fallo;
    
//      public int 
//              public int
//                      public String 

    public Ahorcado() {
        initComponents();

        imagenes = new ImageIcon[7];
        botones = new JButton[26];
        mensajes = new String[15];

        imagenes[0] = new ImageIcon(getClass().getResource("/imagenes/ahorcadoPT1.jpg"));
        imagenes[1] = new ImageIcon(getClass().getResource("/imagenes/ahorcadoPT2.jpg"));
        imagenes[2] = new ImageIcon(getClass().getResource("/imagenes/ahorcadoPT3.jpg"));
        imagenes[3] = new ImageIcon(getClass().getResource("/imagenes/ahorcadoPT4.jpg"));
        imagenes[4] = new ImageIcon(getClass().getResource("/imagenes/ahorcadoPT5.jpg"));
        imagenes[5] = new ImageIcon(getClass().getResource("/imagenes/ahorcadoPT6.jpg"));
        imagenes[6] = new ImageIcon(getClass().getResource("/imagenes/ahorcadoPT7.jpg"));
//        imagenes[7] = new ImageIcon(getClass().getResource("/imagenes/ahorcadoPT8.jpg"));

        botones[0] = A;
        botones[1] = B;
        botones[2] = C;
        botones[3] = D;
        botones[4] = E;
        botones[5] = F;
        botones[6] = G;
        botones[7] = H;
        botones[8] = I;
        botones[9] = J;
        botones[10] = K;
        botones[11] = L;
        botones[12] = M;
        botones[13] = N;
        botones[14] = Ñ;
        botones[15] = O;
        botones[16] = P;
        botones[17] = Q;
        botones[18] = R;
        botones[19] = S;
        botones[20] = T;
        botones[21] = U;
        botones[22] = V;
        botones[23] = W;
        botones[24] = X;
        botones[25] = Y;
//        botones[26] = Z;

        mensajes[0] = "Honduras".toUpperCase();
        mensajes[1] = "Guante".toUpperCase();
        mensajes[2] = "curita".toUpperCase();
        mensajes[3] = "vampiros".toUpperCase();
        mensajes[4] = "polaris".toUpperCase();
        mensajes[5] = "fruto".toUpperCase();
        mensajes[6] = "complejo".toUpperCase();
        mensajes[7] = "exotica".toUpperCase();
        mensajes[8] = "conmigo".toUpperCase();
        mensajes[9] = "Cangrinaje".toUpperCase();
        mensajes[10] = "volando".toUpperCase();
        mensajes[11] = "Arrancarmelo".toUpperCase();
        mensajes[12] = "diamantes".toUpperCase();
        mensajes[13] = "psicopata".toUpperCase();
        mensajes[14] = "mercedes".toUpperCase();
//        mensajes[15] = "romanticos".toUpperCase();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ImagenesAhorcado = new javax.swing.JLabel();
        A = new javax.swing.JButton();
        B = new javax.swing.JButton();
        C = new javax.swing.JButton();
        D = new javax.swing.JButton();
        E = new javax.swing.JButton();
        F = new javax.swing.JButton();
        G = new javax.swing.JButton();
        H = new javax.swing.JButton();
        I = new javax.swing.JButton();
        J = new javax.swing.JButton();
        K = new javax.swing.JButton();
        L = new javax.swing.JButton();
        M = new javax.swing.JButton();
        Ñ = new javax.swing.JButton();
        N = new javax.swing.JButton();
        Q = new javax.swing.JButton();
        P = new javax.swing.JButton();
        O = new javax.swing.JButton();
        R = new javax.swing.JButton();
        S = new javax.swing.JButton();
        T = new javax.swing.JButton();
        U = new javax.swing.JButton();
        V = new javax.swing.JButton();
        W = new javax.swing.JButton();
        X = new javax.swing.JButton();
        Y = new javax.swing.JButton();
        Z = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));

        ImagenesAhorcado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ahorcadoPT1.jpg"))); // NOI18N
        ImagenesAhorcado.setText("jLabel1");

        A.setText("jButton1");
        A.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AActionPerformed(evt);
            }
        });

        B.setText("jButton1");

        C.setText("jButton2");

        D.setText("jButton3");

        E.setText("jButton4");
        E.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EActionPerformed(evt);
            }
        });

        F.setText("jButton5");

        G.setText("jButton5");

        H.setText("jButton5");
        H.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HActionPerformed(evt);
            }
        });

        I.setText("jButton5");

        J.setText("jButton5");

        K.setText("jButton5");

        L.setText("jButton5");

        M.setText("jButton5");

        Ñ.setText("jButton5");

        N.setText("jButton5");

        Q.setText("jButton5");

        P.setText("jButton5");

        O.setText("jButton5");

        R.setText("jButton5");

        S.setText("jButton5");

        T.setText("jButton5");

        U.setText("jButton5");

        V.setText("jButton5");

        W.setText("jButton5");

        X.setText("jButton5");

        Y.setText("jButton5");

        Z.setText("jButton5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(ImagenesAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(244, 244, 244)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(X)
                    .addComponent(T)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(A)
                                .addComponent(E))
                            .addComponent(P))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(B)
                                .addGap(18, 18, 18)
                                .addComponent(C)
                                .addGap(18, 18, 18)
                                .addComponent(D))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(F)
                                        .addGap(18, 18, 18)
                                        .addComponent(G)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(H))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(N)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Ñ)
                                                .addGap(18, 18, 18)
                                                .addComponent(O))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(J)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(K)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(L))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Q)
                                                .addGap(18, 18, 18)
                                                .addComponent(R)
                                                .addGap(18, 18, 18)
                                                .addComponent(S))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(U)
                                                .addGap(18, 18, 18)
                                                .addComponent(V)
                                                .addGap(18, 18, 18)
                                                .addComponent(W))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(Y)
                                                .addGap(18, 18, 18)
                                                .addComponent(Z))))))))
                    .addComponent(M)
                    .addComponent(I))
                .addGap(0, 74, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(ImagenesAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(A)
                            .addComponent(B)
                            .addComponent(C)
                            .addComponent(D))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(E)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(F)
                                .addComponent(G)
                                .addComponent(H)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(I)
                            .addComponent(J)
                            .addComponent(K)
                            .addComponent(L))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(M)
                            .addComponent(N)
                            .addComponent(Ñ)
                            .addComponent(O))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(R)
                            .addComponent(Q)
                            .addComponent(P)
                            .addComponent(S))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T)
                    .addComponent(U)
                    .addComponent(V)
                    .addComponent(W))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(X)
                    .addComponent(Y)
                    .addComponent(Z))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AActionPerformed

    private void HActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HActionPerformed

    private void EActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A;
    private javax.swing.JButton B;
    private javax.swing.JButton C;
    private javax.swing.JButton D;
    private javax.swing.JButton E;
    private javax.swing.JButton F;
    private javax.swing.JButton G;
    private javax.swing.JButton H;
    private javax.swing.JButton I;
    private javax.swing.JLabel ImagenesAhorcado;
    private javax.swing.JButton J;
    private javax.swing.JButton K;
    private javax.swing.JButton L;
    private javax.swing.JButton M;
    private javax.swing.JButton N;
    private javax.swing.JButton O;
    private javax.swing.JButton P;
    private javax.swing.JButton Q;
    private javax.swing.JButton R;
    private javax.swing.JButton S;
    private javax.swing.JButton T;
    private javax.swing.JButton U;
    private javax.swing.JButton V;
    private javax.swing.JButton W;
    private javax.swing.JButton X;
    private javax.swing.JButton Y;
    private javax.swing.JButton Z;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton Ñ;
    // End of variables declaration//GEN-END:variables
}